### ISSUE TITLE
Self Help Support

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Site#1163]
Placeholder issue for: https://trello.com/c/3GlgwGvL/369-self-help-support

Will most likely have to do some styling anyway so...

**Comment by pippinsplugins** [comment]
There needs to be a top level section in `Technical support` for sales tax. Perhaps `Collecting sales tax or VAT`.

Example ticket that illustrates  this: https://secure.helpscout.net/conversation/441997107/67753/?folderId=180499

The answer / resources should include the following:

1. Link to our main tax settings doc
2. Link to 3rd party `#taxes` section
3. (In the future) a link to FastSpring integration

**Comment by cklosowski** [comment]
I'd like to see a PHP 7 Compatibility Tester note.

We have multiple tickets per week that come in stating that the PHP 7 compatibility tester found issues with EDD, but in reality we work just fine, and even run unit tests on php 7.0 and 7.1. The compat tester doesn't know how to read context and check that we do compatibility checks before using the 'flagged' items.

**Comment by kerijacoby** [comment]
- The pre-sale question “Do I still need a membership plugin” has the WooCommerce links from the previous menu option listed under “Additional resources”.

- Add a disclaimer below the "Proceed to support form" button that states "An active license key is required to receive technical support."

**Comment by mintplugins** [comment]
Amazing work Sean. I know this is all still evolving so if you've already considered what I'm about to ask, ignore me :)

I love the singular call to action on the theme section (View Themes):
<img width="752" alt="screen shot 2017-10-02 at 10 26 04 am" src="https://user-images.githubusercontent.com/1638128/31090350-35bb156c-a75c-11e7-9494-548d24d6fb38.png">

Could we do the same thing for each sub-section on the "Do I still need a membership plugin" section?
![aa-learn-more](https://user-images.githubusercontent.com/1638128/31090533-c2a25c06-a75c-11e7-96f6-ea1560d4e66f.jpg)

**Comment by pippinsplugins** [comment]
Let's add an answer to the billing section that explains how customers can get new download links from their account page. Example ticket: https://secure.helpscout.net/conversation/442527002/67804/

**Comment by pippinsplugins** [comment]
Let's add `Recurring Payments` as a top-level option in the `Do I need a membership plugin?` section. Some memberships are purely based around payments and others are based around content access so we need to have both.

**Comment by pippinsplugins** [comment]
Let's add the http://docs.easydigitaldownloads.com/article/312-selling-images-with-edd post to the `Additional Resources` section of `Selling Images with Easy Digital Downloads.

**Comment by pippinsplugins** [comment]
The `Free Downloads` option in extension help needs a answer for `can I add additional fields?`. See https://secure.helpscout.net/conversation/442952664/67836/?folderId=180499

**Comment by pippinsplugins** [comment]
We need to include a section under `Billing` for extension update failures. Three error messages that need addressed:

1. `Update package not available`
2. `Automatic update not available for this plugin`
3. `Download failed: Unauthorized`

These all happen because the license key is not properly activated for the URL being updated.

**Comment by pippinsplugins** [comment]
Can we add info to the extensions section for customers that select a discontinued extension from the list? For example, we don't want customers to submit a ticket for Social Login nor PDF Vouchers as both of those are now sold off site. It would be nice to provide information on the new-help location for those plugins before the customer even submits the ticket.

**Comment by SDavisMedia** [comment]
@kerijacoby Thanks. Adjustments made for both points.

**Comment by SDavisMedia** [comment]
@cklosowski Done.

**Comment by pippinsplugins** [comment]
@SDavisMedia please add a piece that answers `Missing secure Stripe token` to the Stripe extension and link to http://docs.easydigitaldownloads.com/article/1415-stripe-common-issues-and-faq

**Comment by kerijacoby** [comment]
The Recently Viewed Items extension is missing from the extension/theme dropdown.

**Comment by mintplugins** [comment]
Donations is missing from extension/theme dropdown
https://secure.helpscout.net/conversation/447943294/68397?folderId=180499

**Comment by mintplugins** [comment]
Featured Downloads is missing from extension/theme dropdown:
https://secure.helpscout.net/conversation/449627976/68565?folderId=180499

**Comment by SDavisMedia** [comment]
I'll need to think for a few on the best way to handle [this](https://github.com/easydigitaldownloads/EDD-Site/issues/1163#issuecomment-335164859). That can get out of hand really fast if there's a field for each extension that has been moved off-site, since each one would need to provide separate contact information. Thinking.

Everything else has been taken care of. :+1:

**Comment by pippinsplugins** [comment]
`Invoices` extension is missing from the extension selection.

**Comment by pippinsplugins** [comment]
@SDavisMedia can we pre-fill the name / email fields when logged in please?

**Comment by SDavisMedia** [comment]
Done and done.

**Comment by SDavisMedia** [comment]
Closing. I still need to add a path for off-site extensions, which I have on my to-do list. It does not require a issue here, though. Everything is all goody.
