### ISSUE TITLE
Blog post/content pages revamp

### ISSUE THREAD

**Issue by lisag** [easydigitaldownloads/EDD-Site#1188]
As per the EDD Marketing Plan presented at the end of last month, some visual changes were recommended as part of our new plan for content. Suggested changes are listed below. We are aiming for a **January 1st 2018** go-live for the new content streams.

- Recommend removing or repositioning the sidebar on blog post pages for distraction-free reading. Could perhaps move to the bottom of the post?
   - Recommend centre-aligned content
- Understand there is a cart shown in the sidebar on these pages. Wonder if this could be changed to a button somewhere or an icon/menu item in the primary navigation?
- Recommend limiting the number of newsletter signup forms on the blog post page to just one (two max), with potential repositioning of sidebar
- Possible to slightly increase font size of body text on blog post pages?

Examples can be provided if necessary. :)

**Comment by SDavisMedia** [comment]
👍 Sure thing.

**Comment by SDavisMedia** [comment]
@lisag 

"Understand there is a cart shown in the sidebar on these pages. Wonder if this could be changed to a button somewhere or an icon/menu item in the primary navigation?"

The cart is shown beside the logo when there's something in the cart. It's hidden when the cart is empty, as it's pretty useless then.

**Comment by cklosowski** [comment]
We should also be sure to add a rule in to the EDD Custom functions that turns off session generation on any URL containing `/blog` if we're keeping that in the slug. I know that's not something to add into the theme, but figured we should note it here as it looks like this is the canonical issue for the work that'll be done, and that way we keep it in our minds.

by doing so we'll make the site more performant as we push people to it.

**Comment by lisag** [comment]
Another thing - if we can revamp blockquotes so they stand up and break up the page more, that would be wondrous. Similar to Help Scout: 

![screen shot 2017-12-08 at 12 52 42 pm](https://user-images.githubusercontent.com/11830108/33745230-793b60ce-dc1a-11e7-84e6-9f83edda4fb0.png)

So the quote would be centered, larger than body text (but not too large), wider than body text (but not too wide), and a slightly lighter colour than the body text for interest.

The quotee's name would go underneath, right-aligned, with an em dash before it, italicized, and in a smaller font size (if possible).

**Comment by lisag** [comment]
Could we also please look at integrating the Subtitles plugin for WordPress if possible, like we have with RCP and AffiliateWP? This is what is used on those sites: https://wordpress.org/plugins/subtitles/. 

I think it would need to be styled so it looks nice either above or below the main title (when and if it is used).

Since we have predefined content streams launching it might help us educate our readers on the new name of each category.

**Comment by lisag** [comment]
@SDavisMedia Is there somewhere to view how this is looking? Our first post is aiming to be published on 2nd of January so wanted to check it out and see if I have any feedback on minor changes before we publish that first post.

**Comment by SDavisMedia** [comment]
@lisag I'm aware of the timeline. I'll ping you when it's on staging.

**Comment by SDavisMedia** [comment]
@lisag I DMd you. But here's a link to a staging post. http://staging.easydigitaldownloads.com/blog/join-affiliate-program/

**Comment by lisag** [comment]
Amazing!! I love it!
