### ISSUE TITLE
"Register for Support" page shows extra section when logged in

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/EDD-Site#1193]
When already logged in, there is a section of the "Register for Support" page that probably should not be visible: https://easydigitaldownloads.com/support/register/

<img width="1220" alt="screen shot 2017-10-24 at 10 26 56 am" src="https://user-images.githubusercontent.com/88951/31952307-e7f80a00-b8a5-11e7-8acb-62d40964c105.png">

> Use this form to register an account with the Easy Digital Downloads support system.
> Usernames cannot contain any spaces or capital letters.

There 2 statements do not apply, because I'm already logged in. I suspect there is a `is_user_logged_in()` check in the wrong place somewhere.

**Comment by SDavisMedia** [comment]
@JJJ Thanks! It's post content, so that's why you didn't find a string. I'll see about adding that content to the RCP registration form via hook, assuming there is one. If there is, I'll do a logged in check when I write it.

**Comment by SDavisMedia** [comment]
Logged out:

<img width="739" alt="screen shot 2017-11-29 at 12 02 07 pm" src="https://user-images.githubusercontent.com/2359131/33396391-3696cf20-d4fd-11e7-90d6-0c819624c325.png">

Logged in:

<img width="740" alt="screen shot 2017-11-29 at 12 02 31 pm" src="https://user-images.githubusercontent.com/2359131/33396395-3c096760-d4fd-11e7-9d2b-ea7074919f16.png">

----

All based on modifications to the `[register_form]` shortcode. No more post content. 👍
