### ISSUE TITLE
Replace Envato with ConvertKit in popular integrations

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Site#1195]
The popular integrations section of the homepage currently shows Envato:
<img width="848" alt="screen shot 2017-11-02 at 12 05 45 pm" src="https://user-images.githubusercontent.com/1034109/32339577-39d9780a-bfc6-11e7-927f-95a8f0d3c584.png">
That extension is pretty much debunk.

Let's please replace it with ConvertKit.

**Comment by SDavisMedia** [comment]
<img width="1165" alt="screenshot 2017-11-23 19 55 03" src="https://user-images.githubusercontent.com/2359131/33194941-5bfe045a-d088-11e7-89ec-ddbdda433679.png">
