### ISSUE TITLE
Add new pricing FAQ

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/EDD-Site#1197]
https://easydigitaldownloads.com/pricing/

Something like:

## Will Easy Digital Downloads and its extensions work on WordPress.com?

Yes, you can use Easy Digital Downloads and its extensions on WordPress.com if you have a Business plan, which allows third-party plugins to be installed. If you do not have a Business plan on WordPress.com, Easy Digital Downloads and its extensions cannot be used.

___

Last line is optional, thought it should be as clear as possible, but does sounds repeated. AffWP and RCP have this also.

**Comment by amdrew** [comment]
Not 100% sure if extensions can yet, see: https://trello.com/c/zsYuL6Ch/895-let-customers-know-about-using-our-products-with-wordpresscoms-business-plan

**Comment by SDavisMedia** [comment]
<img width="519" alt="screenshot 2017-11-23 19 38 09" src="https://user-images.githubusercontent.com/2359131/33194588-daac526e-d085-11e7-84b1-fefd6925aa4e.png">

**Comment by pippinsplugins** [comment]
:+1:
