### ISSUE TITLE
Increase number of creatives shown in Affiliate Area

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/EDD-Site#1201]
Since there's so many creatives for EDD, the new "25% off" ones get bumped to page 2. To make this easier for affiliates to see and use, we should increase the number of creatives shown.

Current creatives:
https://easydigitaldownloads.com/your-account/affiliate-area/?tab=creatives

Have to click on `2` here to see the new ones:

<img width="914" alt="screenshot 2017-11-15 09 31 12" src="https://user-images.githubusercontent.com/52581/32803256-d3a26c1e-c9e7-11e7-9641-497f49f7e812.png">

___

New ones on page 2

<img width="911" alt="screenshot 2017-11-15 09 31 38" src="https://user-images.githubusercontent.com/52581/32803254-cef4674e-c9e7-11e7-8499-ea1fbf93499f.png">

___

Will need to:

1. Copy over the `dashboard-tab-creatives.php` template file from AffiliateWP's `templates` folder and place in a `affiliatewp` folder on the EDD site
2. Change `$per_page  = 30;` inside the template file to something like `$per_page  = 100`;

**Comment by SDavisMedia** [comment]
got it... will do it shortly

**Comment by SDavisMedia** [comment]
Done. :+1:
