### ISSUE TITLE
Change suggested products on empty cart page

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Site#1210]
<img width="744" alt="screen shot 2017-11-29 at 8 53 01 am" src="https://user-images.githubusercontent.com/2359131/33387669-bcc50b86-d4e2-11e7-96c9-4feed26586b8.png">

-----

Needs Themedd instead of Shoppette. Needs AAP.

**Comment by pippinsplugins** [comment]
Good catch.

**Comment by SDavisMedia** [comment]
<img width="749" alt="screen shot 2017-11-29 at 10 09 31 am" src="https://user-images.githubusercontent.com/2359131/33391311-6ec1577c-d4ed-11e7-9287-20960d0fa671.png">

**Comment by pippinsplugins** [comment]
That looks great!
