### ISSUE TITLE
Simple Notices Pro enhancements

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Site#1217]
Might be making some small changes to how we use this as I put together a new banner for All Access Pass.

**Comment by SDavisMedia** [comment]
Switched to using Font Awesome instead of SVG. Like I've said before, I like SVG. But sometimes I want things to be more flexible and efficient. Using SVG in some places doesn't always fit that.

@pippinsplugins check out the notice on staging: http://staging.easydigitaldownloads.com/ That should look pretty standard from your POV. If you like it, we can go live with it on Monday!

**Comment by pippinsplugins** [comment]
Looks excellent!

**Comment by SDavisMedia** [comment]
Perfect! I'll get the theme edits live and schedule it.
