### ISSUE TITLE
Clean up terms and notices on check out

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Site#1219]
They're messy, especially when notices from Recurring Payments and such are present.

![image](https://user-images.githubusercontent.com/1034109/33526558-e9d8447a-d808-11e7-95f0-33f0999a6c49.png)

**Comment by SDavisMedia** [comment]
🤦‍♂️

**Comment by SDavisMedia** [comment]
@pippinsplugins this should be worst case scenario 👇 

<img width="733" alt="screen shot 2017-12-03 at 1 08 13 pm" src="https://user-images.githubusercontent.com/2359131/33529887-8c1c87f6-d82b-11e7-8532-3f1efddc07f9.png">

<img width="731" alt="screen shot 2017-12-03 at 1 08 37 pm" src="https://user-images.githubusercontent.com/2359131/33529890-901f6742-d82b-11e7-8e2f-a41769a465fd.png">

**Comment by SDavisMedia** [comment]
Average purchase:

<img width="728" alt="screen shot 2017-12-03 at 2 51 29 pm" src="https://user-images.githubusercontent.com/2359131/33530774-7f4e9bfa-d839-11e7-8558-f7f66dd3c0ab.png">

**Comment by SDavisMedia** [comment]
On staging: http://staging.easydigitaldownloads.com/checkout/?edd_action=add_to_cart&download_id=1046254

[Floating gray box](https://cl.ly/262u1K1q3d3r) above the purchase button is because of Terms Per Product. [Fixed here](https://github.com/easydigitaldownloads/edd-terms-per-product/issues/7).

**Comment by pippinsplugins** [comment]
So much better!
