### ISSUE TITLE
Markup and formatting refresh

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Site#1233]
Just a sweep through with @lisag to make sure general markup and formatting is what we want it to be. This issue is mainly for single posts, since the blog recently got a refresh. But I'll hit pages here too.

### Current state of single Posts:
http://staging.easydigitaldownloads.com/blog/markup-formatting-post/

### Current state of single Pages:
http://staging.easydigitaldownloads.com/markup-formatting-page/

**Comment by lisag** [comment]
After staring at this for some time I think the primary thing that needs to be changed for single posts is the margin above and below all headings levels. Could we try adding a little more margin above headings, and reduce the margin slightly beneath the headings? I had a quick look yesterday for H2 at 1.1em above and 0.7em below, but the post disappeared and I didn't get a chance to play with it again to check the other headings levels.

With regard to heading font sizes, H1, H2 and H3 all appear quite similar - is it possible to revisit the font sizes to differentiate them a little further? Maybe just a slight tweak larger/smaller will help with this.

Also, and please correct me if I'm wrong, it looks like H4 and H5 styling might be back to front?

**Comment by SDavisMedia** [comment]
@lisag Yea we lost the page/post today with a refresh of the staging site. I still have it locally. I'll push something up to staging soon with changes and then ping you with that.

**Comment by SDavisMedia** [comment]
Blah. `dev` branch has stuff sitting in it and this branch was built on `dev`.
