### ISSUE TITLE
Queries for expired license keys need updated for EDD SL 3.6

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Site#1234]
There are a number of queries on the account page for getting license details for the current user. These need to be updated for EDD SL 3.6.

**Comment by pippinsplugins** [comment]
PR submitted.

Do not merge yet. A couple of the items that broke on staging should have been taken care of in the BC layer in SL, so we'll use them as a test case.

**Comment by pippinsplugins** [comment]
Back compat layer fixed.

**Comment by pippinsplugins** [comment]
Ok this should be ready for merge as soon as SL 3.6 is put onto live.

**Comment by SDavisMedia** [comment]
This is already on live now. We're running SL 3.6 beta 2.
