### ISSUE TITLE
Separate priority support submission and regular submission

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Site#753]
We've had several people submit feedback about the priority ticket system and they've all mentioned something along the lines of "how do I know I'm getting priority".

An easy way to do this would be to create a separate ticket page for priority support. The existing form wouldn't change at all, we'd just add a second one that is restricted to priority customers to help them feel they're getting special treatment.

It may seem silly but the impression that customers get from the get go is really important. If they don't feel they are getting priority, they probably won't pay for it again.

The new page would require that they are logged in and could show information about there account, including expiration dates and renewal options.

**Comment by SDavisMedia** [comment]
@pippinsplugins checking to see if we still want to follow through with this.

**Comment by pippinsplugins** [comment]
No, closing.
