### ISSUE TITLE
Dashicons instead of PNGs

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/EDD-Site#889]
We should try and use dashicons or SVG icons where we can in lieu of the PNG sprite that s used for certain icons.

So far, I can see it on the Email Newsletter signup forms.

The icons could be replaced with `dashicons-admin-users` and `dashicons-email-alt`

**Comment by SDavisMedia** [comment]
Stopped using the PNGs in fields some time ago. I don't see this being an issue anywhere else. And if I need something similar to this in the future, I won't use PNGs again. Re-open if I'm missing something.
