### ISSUE TITLE
Retina Scaling Issues

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Site#912]
On retina screens some images look stretched out and low quality/scaled:
- Mailinglist icons in fields look scaled
- EDD mascot looks scaled
- Sidebar email newsletter header looks scaled

**Comment by SDavisMedia** [comment]
Gonna close this. Stopped using the field icons some time ago. If we get Edd remade, that would be cool. But it's not an EDD site issue.
